---
include:
  - board: xiao_ble
    shield: charybdis_dongle
    shield: prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2.0.0
    shield: charybdis_left
  - board: nice_nano@2.0.0
    shield: charybdis_right
  - board: nice_nano@2.0.0
    shield: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2.0.0
    shield: corne_right
  - board: nice_nano@2.0.0
    shield: settings_reset
  - board: xiao_bles
    shield: settings_reset
